---
- name: include packages.yml vars
  include_vars: packages.yml
  tags: packages

- name: ensure install common packages
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ packages_common }}"
  tags: packages

- name: autoremove unneeded packages installed as dependencies
  dnf:
    autoremove: true
  tags: packages
