---
- name: include packages.yml vars
  include_vars: packages.yml
  tags: packages

- name: ensure install rpmfusion repositories
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ repo_rpmfusion_free }}"
    - "{{ repo_rpmfusion_nonfree }}"
  tags: packages

- name: ensure install spotify repository
  get_url:
    url: "{{ repo_spotify_url }}"
    dest: "/etc/yum.repos.d/fedora-spotify.repo"
    owner: root
    group: root
    mode: 0644
  tags: packages

- name: ensure install fedora third party repository
  dnf:
    name: fedora-workstation-repositories
    state: present
  tags: packages

- name: ensure install common packages
  dnf:
    name: "{{ item }}"
    state: present
    enablerepo:
      - fedora-cisco-openh264
      - google-chrome
  with_items:
    - "{{ packages_common }}"
  tags: packages

- name: ensure install third party packages
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ package_dropbox_url }}"
    - "{{ package_keybase_url }}"
    - "{{ package_skype_url }}"
    - "{{ package_zoom_url }}"
  tags: packages

- name: autoremove unneeded packages installed as dependencies
  dnf:
    autoremove: true
  tags: packages
